#! /usr/bin/env bash
# Script my typical cmake build process.

help() {
    echo -e \
"Usage

    mbuild [options]

Options

    -c, --config-only   Configure project; don't make or install
    -m, --make-only     Configure and make project; don't install
    -s, --skip-tests    Don't run ctest
    -dd, --dest-dir     Use a local install directory (_install)
    -h, --help          Show this help message
    -v, --verbose       Enable verbose output
"
    exit 0
}

config_only=false
make_only=false
skip_tests=false
dest_dir=$CONDA_PREFIX
verbose=

i=1;
for argument in "$@"; do
    case $argument in
        -h|--help)
            help
            ;;
        -c|--config-only)
            config_only=true
            ;;
        -m|--make-only)
            make_only=true
            ;;
        -s|--skip-tests)
            skip_tests=true
            ;;
        -v|--verbose)
            verbose=-V
            ;;
        -dd|--dest-dir)
            dest_dir=$PWD/_install
            ;;
        -?*)
            help
            ;;
        *)
            help
            ;;
    esac

    i=$((i + 1));
done

build_type=Release
build_dir=_build

cmake -B $build_dir --fresh -DCMAKE_BUILD_TYPE=$build_type -DCMAKE_INSTALL_PREFIX=$dest_dir
if $config_only; then exit 0; fi

cmake --build $build_dir
if [ $? != 0 ]; then exit 1; fi
if $make_only; then exit 0; fi

if [ $skip_tests = false ]; then
    ctest $verbose --test-dir $build_dir
fi

if [ $? != 0 ]; then
    exit 1
else
    cmake --install $build_dir --prefix $dest_dir
fi

exit 0
