#! /usr/bin/env bash
# Script my typical cmake build process.

help() {
    echo -e "Usage: mbuild [-c | --config-only] [-m | --make-only]
              [-s | --skip-tests] [-dd | --dest-dir]
              [-h | --help]"
    exit 0
}

config_only=false
make_only=false
skip_tests=false
dest_dir=$CONDA_PREFIX

i=1;
for argument in "$@"; do
    case $argument in
        -h|--help)
            help
            ;;
        -c|--config-only)
            config_only=true
            ;;
        -m|--make-only)
            make_only=true
            ;;
        -s|--skip-tests)
            skip_tests=true
            ;;
        -dd|--dest-dir)
            dest_dir=$PWD/_install
            ;;
        -?*)
            help
            ;;
        *)
            help
            ;;
    esac

    i=$((i + 1));
done

build_type=Release
build_dir=_build

cmake -B $build_dir --fresh -DCMAKE_BUILD_TYPE=$build_type
if $config_only; then exit 0; fi

cmake --build $build_dir
if [ $? != 0 ]; then exit 1; fi
if $make_only; then exit 0; fi

if [ $skip_tests = false ]; then
    ctest --test-dir $build_dir
fi

if [ $? != 0 ]; then
    exit 1
else
    cmake --install $build_dir --prefix $dest_dir
fi

exit 0
