#! /usr/bin/env bash
# Script my typical cmake build process.

help() {
    echo -e "Usage: mbuild [-d | --dest-dir] [-h | --help]"
    exit 0
}

dest_dir=

i=1;
for argument in "$@"; do
    case $argument in
        -h|--help)
            help
            ;;
        -d|--dest-dir)
            dest_dir=$PWD/_install
            ;;
        -?*)
            help
            ;;
        *)
            help
            ;;
    esac

    i=$((i + 1));
done

build_type=Release
build_dir=_build

if [ -e $dest_dir ]; then rm -rf $dest_dir; fi

if [ -e $build_dir ]; then rm -r $build_dir; fi
mkdir $build_dir && cd $build_dir

cmake .. \
    -DCMAKE_BUILD_TYPE=$build_type \
    -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX

make -s
if [ $? != 0 ]; then exit 1; fi

if test -n "$(find . -maxdepth 1 -name 'test*' -print -quit)"; then
    ctest
fi

if [ $? != 0 ]; then
    exit 1
else
    make DESTDIR=$dest_dir install
fi

exit 0

