#! /usr/bin/env bash
# Render a Markdown or reStructuredText file as HTML and view in a browser.

help="Usage: mview [-u] [-h] FILE"
browser="Firefox"
css="https://raw.githubusercontent.com/mdpiper/scripts/refs/heads/main/assets/markdown-preview.css"
show=1
markup="markdown"
extension="${1##*.}"
if [[ $extension = "rst" ]]; then
    markup=$extension
fi

while getopts ":uh" opt; do
  case $opt in
  u)
      show=0
      ;;
  h)
      echo -e $help
      exit 0
      ;;
  \?)
      # Catches invalid flag.
      echo "Invalid option: -$OPTARG" >&2
      echo -e $help
      exit 1
      ;;
  esac
done
shift $((OPTIND - 1))

pandoc $1 --from $markup --to html --standalone --css=$css -o $1.html --quiet

if [[ $show = 1 ]]; then
    open $1.html
fi

exit 0
