#! /usr/bin/env bash
# Render a Markdown or reStructuredText file as HTML and view in a browser.

help="Usage: mview FILE [-u] [-h]"
browser="Firefox"
show=1
markup="markdown"
extension="${1##*.}"
if [[ $extension = "rst" ]]; then
    markup=$extension
fi

while getopts ":uh" opt; do
  case $opt in
  u)
      show=0
      echo "hi!"
      ;;
  h)
      echo -e $help
      exit 0
      ;;
  \?)
      # Catches invalid flag.
      echo "Invalid option: -$OPTARG" >&2
      echo -e $help
      exit 1
      ;;
  esac
done
shift $((OPTIND - 1))

pandoc $1 --from $markup --to html -o $1.html

if [[ $show = 1 ]]; then
    echo "show = $show"
    open $1.html
fi

exit 0
