#! /usr/bin/env bash
# Remove a user from a tljh instance.

help="Usage: rmhubuser USER VOLUME"
if [[ $1 = "-h" ]]; then
    echo -e $help
    exit 0
fi

if id $user &>/dev/null; then
    sudo -E du -hs /home/$1
    sudo -E rm -rf /home/$1
    sudo -E userdel $1
    df | grep $2  # volume name; e.g., nvme0n1p1 for `lab` instance
    echo "User $1 removed"
else
    echo "User $1 not found"
fi
exit 0
