#! /usr/bin/env bash
# Remove a user from a tljh instance.

help="Usage: rmhubuser USER"
if [[ $1 = "-h" ]]; then
    echo -e $help
    exit 0
fi

user=jupyter-$1

if id $user &>/dev/null; then
    sudo -E du -hs /home/$user
    sudo -E deluser $user --remove-home
    echo "User $1 removed"
else
    echo "User $1 not found"
fi
exit 0
