#!/usr/bin/env bash
# Removes a directory from the PATH environment variable.
#
# This script must be called with `source`:
#
#    $ source rmpath [-q] /the/path

if [[ "$(basename "$0" 2> /dev/null)" == "rmpath" ]]; then
    (>&2 echo "Usage: rmpath must be sourced. Run 'source rmpath /the/path'.")
    exit 1
fi

quiet="false"
if [[ $1 = "-q" ]]; then
    quiet="true"
    shift
fi

if [[ $# -ne 1 ]]; then
    (>&2 echo "rmpath: specify one path to be removed.")
    return 1
fi

if [[ $quiet = "false" ]]; then
    echo "Removing $1 from PATH"
fi
replace="$1:"
empty=""
newpath=${PATH/$replace/$empty}
export PATH=$newpath
